name: Reusable Service Provision Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      terraform_version:
        default: '1.6.0'
        type: string
      terragrunt_version:
        default: '0.54.15'
        type: string

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Install Terragrunt
        run: |
          curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt_version }}/terragrunt_linux_amd64
          chmod +x /tmp/terragrunt
          sudo mv /tmp/terragrunt /usr/local/bin/terragrunt

      - name: Terragrunt Plan
        working-directory: ${{ inputs.working_directory }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_subscription_id: ${{ inputs.subscription_id }}

          ARM_USE_AZURE_CLI_AUTH: false
        run: |
          terragrunt plan --terragrunt-non-interactive

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: approver

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Install Terragrunt
        run: |
          curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt_version }}/terragrunt_linux_amd64
          chmod +x /tmp/terragrunt
          sudo mv /tmp/terragrunt /usr/local/bin/terragrunt

      - name: Terragrunt Apply
        working-directory: ${{ inputs.working_directory }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_AZURE_CLI_AUTH: false
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve
